In [1]:
# Import package 
import swehockey.swehockey_scraper as swe
import numpy as np
import pandas as pd

In [2]:
# Read in needed schedule-ids
df_swehockey = pd.read_csv("https://raw.githubusercontent.com/msjoelin/swehockey_scraper/master/data/scheduleid.csv", 
                           error_bad_lines=False,
                          dtype=str)

df_swehockey.head()

  schedule_id league   season
0       10371    shl  2019/20
1        9171    shl  2018/19
2        8121    shl  2017/18
3        7132    shl  2016/17
4        6052    shl  2015/16

In [4]:
# get games for some schedule ids
games = swe.getGames(df_swehockey.head())
games.head()

Collects data from http://stats.swehockey.se/ScheduleAndResults/Schedule/10371
10371  collected
Collects data from http://stats.swehockey.se/ScheduleAndResults/Schedule/9171
9171  collected
Collects data from http://stats.swehockey.se/ScheduleAndResults/Schedule/8121
8121  collected
Collects data from http://stats.swehockey.se/ScheduleAndResults/Schedule/7132
7132  collected
Collects data from http://stats.swehockey.se/ScheduleAndResults/Schedule/6052
6052  collected

,date,game,score,periodscore,spectators,schedule_id,game_id,league,season
0,2019-09-14,Frölunda HC - Brynäs IF,2 - 5,"(0-2, 0-3, 2-0)",12044,10371,441805,shl,2019/20
1,2019-09-14,Skellefteå AIK - IK Oskarshamn,5 - 4,"(0-1, 3-3, 1-0, 1-0)",5137,10371,441808,shl,2019/20
2,2019-09-14,Leksands IF - IF Malmö Redhawks,5 - 2,"(1-2, 0-0, 4-0)",7650,10371,441809,shl,2019/20
3,2019-09-14,Djurgårdens IF - Linköping HC,4 - 2,"(0-1, 3-1, 1-0)",7018,10371,441803,shl,2019/20
4,2019-09-14,Färjestad BK - Örebro HK,4 - 6,"(2-2, 1-2, 1-2)",8250,10371,441804,shl,2019/20

In [8]:
# Clean up the output with cleanGames
df_games_clean = swe.cleanGames(games.copy())
df_games_clean.head()

,date,game,score,periodscore,spectators,schedule_id,game_id,league,season,home,...,p4score_home,p4score_away,p5score_home,p5score_away,result,result_p1,result_p2,result_p3,result_p4,result_p5
0,2019-09-14,Frölunda HC - Brynäs IF,2 - 5,"0-2, 0-3, 2-0",12044,10371,441805,shl,2019/20,Frölunda HC,...,NaN,NaN,NaN,NaN,away,away,away,home,None,None
1,2019-09-14,Skellefteå AIK - IK Oskarshamn,5 - 4,"0-1, 3-3, 1-0, 1-0",5137,10371,441808,shl,2019/20,Skellefteå AIK,...,1.0,0.0,NaN,NaN,draw,away,draw,home,home,None
2,2019-09-14,Leksands IF - IF Malmö Redhawks,5 - 2,"1-2, 0-0, 4-0",7650,10371,441809,shl,2019/20,Leksands IF,...,NaN,NaN,NaN,NaN,home,away,draw,home,None,None
3,2019-09-14,Djurgårdens IF - Linköping HC,4 - 2,"0-1, 3-1, 1-0",7018,10371,441803,shl,2019/20,Djurgårdens IF,...,NaN,NaN,NaN,NaN,home,away,home,home,None,None
4,2019-09-14,Färjestad BK - Örebro HK,4 - 6,"2-2, 1-2, 1-2",8250,10371,441804,shl,2019/20,Färjestad BK,...,NaN,NaN,NaN,NaN,away,draw,away,away,None,None

In [9]:
# Create dataframe on teamlevel
df_teams = swe.getTeamData(df_games_clean)
df_teams.head()

,date,game,score,periodscore,spectators,schedule_id,game_id,league,season,team,...,H2H_W,H2H_D,H2H_L,points,points_cum,points_cum_prev,points_cum_prev_avg,points_cum_h_a,points_cum_h_a_prev,points_cum_h_a_prev_avg
0,2015-09-17,Brynäs IF - IF Malmö Redhawks,6 - 3,"3-1, 2-2, 1-0",5898,6052,252967,shl,2015/16,Brynäs IF,...,0.0,0.0,0.0,3,3,0,NaN,3,0,NaN
1,2015-09-19,Färjestad BK - Brynäs IF,3 - 2,"0-0, 2-2, 1-0",8049,6052,252975,shl,2015/16,Brynäs IF,...,0.0,0.0,0.0,0,3,3,3.00,0,0,NaN
2,2015-09-24,Djurgårdens IF - Brynäs IF,1 - 2,"0-1, 1-1, 0-0",6072,6052,252978,shl,2015/16,Brynäs IF,...,0.0,0.0,0.0,3,6,3,1.50,3,0,0.0
3,2015-09-26,Brynäs IF - HV 71,3 - 1,"0-0, 1-0, 2-1",5232,6052,252988,shl,2015/16,Brynäs IF,...,0.0,0.0,0.0,3,9,6,2.00,6,3,3.0
4,2015-10-01,Linköping HC - Brynäs IF,4 - 3,"1-0, 1-3, 1-0, 0-0, 1-0",5613,6052,252996,shl,2015/16,Brynäs IF,...,0.0,0.0,0.0,1,10,9,2.25,4,3,1.5

In [7]:
# Get game details
game_events, game_summary = swe.getGameData(games['game_id'].head())

collected  0 441805
collected  1 441808
collected  2 441809
collected  3 441803
collected  4 441804
    time      event team                                            players  \
4  60:00     GK Out  FRÖ                                41.  Rubin,  Niklas
5  60:00     GK Out  BIF                             30.  Eriksson,  Joacim
6  56:11  2-5 (PP1)  FRÖ  59.  Hjalmarsson,  Simon  (1)  20.  Lundqvist,...
7  55:58      2 min  BIF                            56.  Sigalet,  Jonathan
8  46:34   1-5 (EQ)  FRÖ  15.  Grönlund,  Anders  (1)  40.  Mustonen,  J...

                                              on_ice game_id
4                                                NaN  441805
5                                                NaN  441805
6  Pos. Part.: 3  , 20  , 41  , 49  , 59  , 81  N...  441805
7                           Hooking  (55:58 - 56:11)  441805
8  Pos. Part.: 12  , 15  , 20  , 40  , 41  , 63  ...  441805
  shots_h shots_h_period shots_a shots_a_period league game_id
1      24       (5:9:10)      19        (9:7:3)    SHL  441805
1      36    (7:13:13:3)      23     (5:11:6:1)    SHL  441808
1      32      (8:12:12)      28       (14:9:5)    SHL  441809
1      37      (12:17:8)      21        (9:9:3)    SHL  441803
1      33      (12:9:12)      22        (8:8:6)    SHL  441804

In [10]:
game_events.head()

,time,event,team,players,on_ice,game_id
4,60:00,GK Out,FRÖ,"41. Rubin, Niklas",NaN,441805
5,60:00,GK Out,BIF,"30. Eriksson, Joacim",NaN,441805
6,56:11,2-5 (PP1),FRÖ,"59. Hjalmarsson, Simon (1) 20. Lundqvist,...","Pos. Part.: 3 , 20 , 41 , 49 , 59 , 81 N...",441805
7,55:58,2 min,BIF,"56. Sigalet, Jonathan",Hooking (55:58 - 56:11),441805
8,46:34,1-5 (EQ),FRÖ,"15. Grönlund, Anders (1) 40. Mustonen, J...","Pos. Part.: 12 , 15 , 20 , 40 , 41 , 63 ...",441805

In [11]:
game_summary.head()

  shots_h shots_h_period shots_a shots_a_period league game_id
1      24       (5:9:10)      19        (9:7:3)    SHL  441805
1      36    (7:13:13:3)      23     (5:11:6:1)    SHL  441808
1      32      (8:12:12)      28       (14:9:5)    SHL  441809
1      37      (12:17:8)      21        (9:9:3)    SHL  441803
1      33      (12:9:12)      22        (8:8:6)    SHL  441804